import { IFetchResponse } from '@/interfaces/response.interface';
import { ICSRFTokenResponse } from '@/interfaces/web/auth.interface';

interface HttpConfig {
  apiUrl?: string;
  endpoint?: string;
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  contentType?: string;
  jwtToken?: string;
  data?: unknown;
}

let cachedCsrfToken: string | null = null;

async function getOrFetchCsrfToken(): Promise<string> {
  if (cachedCsrfToken) {
    return cachedCsrfToken;
  }

  const url = `${process.env.NEXT_PUBLIC_API_URL}/csrf-token`;
  const options: RequestInit = {
    method: 'GET',
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json',
    },
  };

  const response = await fetch(url, options);
  if (!response.ok) {
    throw new Error(`Failed to fetch CSRF token. Status: ${response.status}`);
  }

  const apiResponse: IFetchResponse<ICSRFTokenResponse> = await response.json();

  if (apiResponse.data && apiResponse.data.csrfToken) {
    const token = apiResponse.data.csrfToken;
    cachedCsrfToken = token;
    return token;
  }

  throw new Error('CSRF token property missing from API response.');
}

/**
 * @param endpoint The API endpoint (e.g., '/users')
 * @param method The HTTP method (GET, POST, PUT, DELETE)
 * @param jwtToken The token generated by the server to authenticate user
 * @param contentType The content type of the request
 * @param data The data (body) to send (for POST, PUT)
 * @returns The JSON response data
 */
export async function httpRequest({
  apiUrl,
  endpoint,
  method = 'GET',
  contentType = 'application/json',
  jwtToken,
  data,
}: HttpConfig): Promise<any> {
  const isExternal = apiUrl;
  let csrfToken: string | undefined;
  if (
    !isExternal &&
    (method == 'POST' || method == 'PUT' || method == 'DELETE')
  ) {
    try {
      csrfToken = await getOrFetchCsrfToken();
    } catch {
      throw new Error('Erro ao gerar o CSRF Token');
    }
  }

  const url = endpoint
    ? `${process.env.NEXT_PUBLIC_API_URL}/${endpoint}`
    : (apiUrl ?? '/');

  const isFormData =
    typeof FormData !== 'undefined' && data instanceof FormData;

  const headers: HeadersInit = {
    ...(!isExternal && jwtToken && { Authorization: `Bearer ${jwtToken}` }),
    ...(!isExternal && csrfToken && { 'X-CSRF-Token': csrfToken }),
  };

  if (!isFormData) {
    headers['Content-Type'] = contentType;
  }

  const options: RequestInit = {
    method,
    credentials: isExternal ? 'omit' : 'include',
    headers,
  };

  if (data) {
    options.body = isFormData ? (data as FormData) : JSON.stringify(data);
  }

  try {
    const response = await fetch(url, options);

    if (!response.ok) {
      const errorData = await response.json();
      const errorMessage =
        errorData.message || errorData.error || 'Erro interno do servidor';
      throw new Error(
        Array.isArray(errorMessage) ? errorMessage.join(', ') : errorMessage
      );
    }

    if (
      response.status === 204 ||
      response.headers.get('content-length') === '0'
    ) {
      return null;
    }

    const jsonData = await response.json();
    return jsonData;
  } catch (error) {
    if (error instanceof Error) {
      console.error(`apiService error: ${error.message}`);
    }
    throw error;
  }
}
