import { USER_ROLES } from '@/enum/role.enum';
import { IAdminUsersHome } from '@/interfaces/admin/admin-users.interface';
import { IFetchResponse } from '@/interfaces/response.interface';

export const response: IFetchResponse<IAdminUsersHome> = {
  status: true,
  message: 'Recebido com sucesso',
  date: '2025-02-20',
  data: {
    idUser: 1,
    condoList: [
      {
        idCondo: 1,
        name: 'Horto Florestal 1',
        blockUnit: 'Quadra',
        lotUnit: 'Lote',
      },
      {
        idCondo: 2,
        name: 'Horto Florestal 2',
        blockUnit: 'Quadra',
        lotUnit: 'Lote',
      },
    ],
    condo: {
      idCondo: 1,
      name: 'Horto Florestal 1',
      blockUnit: 'Quadra',
      lotUnit: 'Lote',
    },
    users: [
      {
        idUser: 1,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 1',
        phone: '11941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 2,
        createdAt: '2025-02-28',
        name: 'Daniela Nakano',
        phone: '5511975133795',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: false,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 3,
        createdAt: '2025-02-28',
        name: 'Lucas Ryo',
        phone: '5511941221211',
        isWhatsapp: false,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 4,
        createdAt: '2025-02-28',
        name: 'Lucas Ryo Horauti',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 5,
        createdAt: '2025-02-28',
        name: 'Assunção',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 6,
        createdAt: '2025-02-28',
        phone: '5511941221211',
        isWhatsapp: true,
        name: 'Fátima',
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: false,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '23',
        },
      },
      {
        idUser: 7,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 3',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 8,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 4',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 9,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 1',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 10,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 2 asdfas fasd asf as fas d',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: false,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 11,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 3',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 12,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 4',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 13,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 1',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 14,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 2 asdfas fasd asf as fas d',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: false,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 15,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 3',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
      {
        idUser: 16,
        createdAt: '2025-02-28',
        name: 'Rafael Horauti 4',
        phone: '5511941221211',
        isWhatsapp: true,
        email: 'rafael_h44@hotmail.com',
        photoUrl: 'https://github.com/shadcn.png',
        fallbackName: 'RH',
        isActive: true,
        role: USER_ROLES.USER,
        address: {
          idAddress: 1,
          block: '10',
          lot: '26',
        },
      },
    ],
  },
};
