export const userDetailsMock = {
  idUser: 1,
  createdAt: '2025-05-10',
  name: 'Rafael Horauti',
  birthDate: new Date(),
  email: 'rafafel_h44@hotmail.com',
  phone: '5511941221211',
  photoUrl: '',
  fallbackName: 'RH',
  isActive: true,
  isEmailConfirmed: true,
  accessLevel: 1,
  address: {
    idAddress: 1,
    type: 'HOUSE',
    street: 'Rua Geraldo Pachedo Valente',
    number: '452',
    city: 'Sorocaba',
    state: 'SP',
    blockType: 'Quadra',
    block: '10',
    lotType: 'Lote',
    lot: '26',
  },
};
